server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: tiny-url-service
            uri: http://localhost:8081
            predicates:
              - Path=/tiny/url/**

          - id: user-identity-service
            uri: http://localhost:8082
            predicates:
              - Path=/user/identity/**
